'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Search,MapPin,Phone,ShieldCheck,AlertTriangle,Building2,Download,Star,Save,CalendarDays,StickyNote,CheckCircle2,Filter,Database,Upload} from 'lucide-react';
import {NIGERIA_LOCATIONS,NIGERIA_STATES} from '../data/nigeria';
import {NIGERIA_AGENCY_BATCH_1} from '../data/nigeria-agencies-batch1';
import {NIGERIA_AGENCY_BATCH_2026_09_01} from '../data/nigeria-batch-2026-09-01';
type LeadStatus='New'|'Contacted'|'Qualified'|'Converted';
type LeadCategory='Travel Agency'|'Embassy'|'High Commission'|'Visa Centre'|'Visa Consultant';
type LeadMeta={saved?:boolean;status?:LeadStatus;notes?:string;followUpDate?:string};
type Lead={id:string;name:string;city:string;state:string;area?:string;address?:string;phone?:string;services:string[];rating?:number;reviews?:number;source?:string;verification?:string;sourceUrl?:string};
const localLeads:Lead[]=[...NIGERIA_AGENCY_BATCH_1,...NIGERIA_AGENCY_BATCH_2026_09_01].map((x:any,i)=>({...x,id:x.id||`ng-${i}-${String(x.name).toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,city:x.city||'Unknown',state:x.state||'Unknown',services:Array.isArray(x.services)?x.services:['Travel agency']}));
const STORAGE_KEY='agency-finder-lead-pipeline-v1',IMPORT_KEY='agency-finder-amadeus-import-v1';
function category(x:Lead):LeadCategory{const s=`${x.name} ${(x.services||[]).join(' ')}`.toLowerCase();if(s.includes('high commission'))return'High Commission';if(s.includes('embassy'))return'Embassy';if(s.includes('visa centre')||s.includes('visa center'))return'Visa Centre';if(s.includes('visa consultant')||s.includes('visa consultancy'))return'Visa Consultant';return'Travel Agency'}
function score(x:Lead){const r=Math.min(100,(x.rating||0)/5*100),v=x.verification==='VERIFIED'?100:x.verification==='DIRECTORY LISTED'?70:55,c=x.phone?90:35,rv=Math.min(100,35+Math.log10(Math.max(1,x.reviews||0))*20);return Math.round(r*.3+rv*.2+c*.2+v*.3)}
function splitDelimited(line:string,d=','){const o:string[]=[];let c='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===d&&!q){o.push(c.trim());c=''}else c+=ch}o.push(c.trim());return o}
function parseImport(text:string):Lead[]{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const d=lines[0].includes('\t')?'\t':lines[0].split(',').length>1?',':';',h=splitDelimited(lines[0],d).map(x=>x.toLowerCase().replace(/[^a-z0-9]+/g,'')),pick=(r:string[],n:string[])=>{const i=h.findIndex(x=>n.some(y=>x.includes(y)));return i>=0?(r[i]||'').trim():''};return lines.slice(1).map((line,i)=>{const r=splitDelimited(line,d),name=pick(r,['agencyname','companyname','agency','name','travelagency','office']);if(!name)return null as any;const phone=pick(r,['phone','telephone','mobile','contact']);return{id:`amadeus-${i}-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${phone.replace(/\D/g,'')}`,name,city:pick(r,['city','town'])||'Abuja',state:pick(r,['state','province','region'])||'Federal Capital Territory',address:pick(r,['address','street','location']),phone,services:['Travel agency'],source:'Amadeus import',verification:'AMADEUS IMPORTED',sourceUrl:pick(r,['website','url','web'])||undefined} as Lead}).filter(Boolean)}
function exportCSV(rows:Lead[],meta:Record<string,LeadMeta>){const cols=['name','category','state','city','area','address','phone','services','rating','reviews','source','verification','sourceUrl','score','leadStatus','saved','notes','followUpDate'],esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[cols.join(','),...rows.map(x=>{const m=meta[x.id]||{};return cols.map(c=>esc(c==='category'?category(x):c==='services'?x.services.join('; '):c==='score'?score(x):c==='leadStatus'?m.status||'New':c==='saved'?(m.saved?'YES':'NO'):c==='notes'?m.notes||'':c==='followUpDate'?m.followUpDate||'':(x as any)[c])).join(',')})].join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='nigeria-travel-agency-leads.csv';a.click();URL.revokeObjectURL(url)}
export default function Home(){const[q,setQ]=useState(''),[categoryFilter,setCategoryFilter]=useState('All'),[state,setState]=useState('All Nigeria'),[city,setCity]=useState('All cities'),[service,setService]=useState('All services'),[verification,setVerification]=useState('All'),[minScore,setMinScore]=useState(0),[pipeline,setPipeline]=useState<LeadStatus|'All'>('All'),[savedOnly,setSavedOnly]=useState(false),[meta,setMeta]=useState<Record<string,LeadMeta>>({}),[openId,setOpenId]=useState<string|null>(null),[remote,setRemote]=useState<Lead[]>([]),[imported,setImported]=useState<Lead[]>([]),[loadingRemote,setLoadingRemote]=useState(true),[importMessage,setImportMessage]=useState('');const fileRef=useRef<HTMLInputElement>(null);
useEffect(()=>{try{const m=localStorage.getItem(STORAGE_KEY);if(m)setMeta(JSON.parse(m));const i=localStorage.getItem(IMPORT_KEY);if(i)setImported(JSON.parse(i))}catch{}fetch('/api/nigeria-agencies?limit=4000').then(r=>r.ok?r.json():null).then(d=>{if(d?.agencies)setRemote(d.agencies)}).catch(()=>{}).finally(()=>setLoadingRemote(false))},[]);
const persist=(m:Record<string,LeadMeta>)=>{setMeta(m);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(m))}catch{}};const updateLead=(id:string,p:LeadMeta)=>persist({...meta,[id]:{...(meta[id]||{}),...p}});
const importFile=(f:File)=>{const r=new FileReader();r.onload=()=>{try{const p=parseImport(String(r.result||''));if(!p.length){setImportMessage('No agency rows detected. Export Amadeus as CSV/TSV.');return}const n=[...imported],seen=new Set(n.map(x=>`${x.name}|${x.city}|${x.phone||''}`.toLowerCase()));for(const x of p){const k=`${x.name}|${x.city}|${x.phone||''}`.toLowerCase();if(!seen.has(k)){seen.add(k);n.push(x)}}setImported(n);try{localStorage.setItem(IMPORT_KEY,JSON.stringify(n))}catch{}setImportMessage(`${p.length} Amadeus rows imported · ${n.length} saved`)}catch{setImportMessage('Could not read this file. Please export Amadeus as CSV or TSV.')}};r.readAsText(f)};
const leads=useMemo(()=>{const out:Lead[]=[],seen=new Set<string>();for(const x of [...localLeads,...remote,...imported]){const k=`${x.name}|${x.state}|${x.city}|${x.phone||''}`.toLowerCase().replace(/[^a-z0-9|]+/g,'');if(!seen.has(k)){seen.add(k);out.push(x)}}return out},[remote,imported]);
const cities=useMemo(()=>state==='All Nigeria'?['All cities',...Array.from(new Set(Object.values(NIGERIA_LOCATIONS).flat())).sort()]:['All cities',...(NIGERIA_LOCATIONS[state as keyof typeof NIGERIA_LOCATIONS]||[])],[state]);const services=useMemo(()=>['All services',...Array.from(new Set(leads.flatMap(x=>x.services))).sort()],[leads]);
const rows=useMemo(()=>leads.filter(x=>categoryFilter==='All'||category(x)===categoryFilter).filter(x=>`${x.name} ${x.city} ${x.state} ${x.area||''} ${x.address||''} ${x.services.join(' ')}`.toLowerCase().includes(q.toLowerCase())).filter(x=>state==='All Nigeria'||x.state===state).filter(x=>city==='All cities'||x.city===city).filter(x=>service==='All services'||x.services.includes(service)).filter(x=>verification==='All'||x.verification===verification).filter(x=>score(x)>=minScore).filter(x=>pipeline==='All'||(meta[x.id]?.status||'New')===pipeline).filter(x=>!savedOnly||!!meta[x.id]?.saved).sort((a,b)=>score(b)-score(a)),[leads,q,categoryFilter,state,city,service,verification,minScore,pipeline,savedOnly,meta]);
const verified=leads.filter(x=>x.verification==='VERIFIED').length,listed=leads.filter(x=>x.verification==='DIRECTORY LISTED').length,covered=new Set(leads.map(x=>x.state).filter(Boolean)).size,converted=leads.filter(x=>meta[x.id]?.status==='Converted').length;
return <main style={{minHeight:'100vh',background:'#f6f7f9',color:'#17202a',fontFamily:'Inter,system-ui,sans-serif',padding:'30px 5vw'}}><div style={{maxWidth:1280,margin:'0 auto'}}><header style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'end',marginBottom:22}}><div><div style={{fontSize:11,fontWeight:800,letterSpacing:'.12em',color:'#738091'}}>SALES RADAR · NIGERIA-WIDE INTELLIGENCE</div><h1 style={{fontSize:34,margin:'8px 0'}}>Travel Agency Lead Finder</h1><p style={{margin:0,color:'#7d8793'}}>Find, save, qualify and follow up travel-agency opportunities across Nigeria.</p></div><div style={{display:'flex',gap:8}}><input ref={fileRef} type='file' accept='.csv,.tsv,.txt' onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f);e.currentTarget.value=''}} style={{display:'none'}}/><button onClick={()=>fileRef.current?.click()} style={btn}><Upload size={15}/> Import Amadeus</button><button onClick={()=>exportCSV(rows,meta)} style={btn}><Download size={15}/> Export Excel/CSV</button></div></header>{importMessage&&<div style={notice}>{importMessage}</div>}
<section style={filters}><div style={searchBox}><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Agency, city, area, service...' style={{border:0,outline:0,padding:10,width:'100%'}}/></div><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option>All</option><option>Travel Agency</option><option>Embassy</option><option>High Commission</option><option>Visa Centre</option><option>Visa Consultant</option></select><select value={state} onChange={e=>{setState(e.target.value);setCity('All cities')}}><option>All Nigeria</option>{NIGERIA_STATES.map(s=><option key={s}>{s}</option>)}</select><select value={city} onChange={e=>setCity(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select><select value={service} onChange={e=>setService(e.target.value)}>{services.map(s=><option key={s}>{s}</option>)}</select><select value={verification} onChange={e=>setVerification(e.target.value)}><option>All</option><option>VERIFIED</option><option>DIRECTORY LISTED</option><option>AMADEUS IMPORTED</option><option>NEEDS VERIFICATION</option></select></section>
<section style={stats}><Stat icon={<Building2/>} value={leads.length} label={loadingRemote?'Loading national index…':'Leads indexed'}/><Stat icon={<Database/>} value={listed} label='Directory-listed'/><Stat icon={<ShieldCheck/>} value={verified} label='Cross-checked'/><Stat icon={<MapPin/>} value={covered} label='States with data'/><Stat icon={<CheckCircle2/>} value={converted} label='Converted'/></section>
<section style={panel}><div style={panelTitle}><Filter size={15}/> Lead Pipeline</div><div style={wrap}>{(['All','New','Contacted','Qualified','Converted'] as const).map(s=><button key={s} onClick={()=>setPipeline(s)} style={{...pill,...(pipeline===s?activePill:{})}}>{s}{s!=='All'&&<span style={{opacity:.65,marginLeft:5}}>{leads.filter(x=>(meta[x.id]?.status||'New')===s).length}</span>}</button>)}<button onClick={()=>setSavedOnly(!savedOnly)} style={{...pill,...(savedOnly?activePill:{})}}><Save size={12}/> Saved only</button><select value={minScore} onChange={e=>setMinScore(Number(e.target.value))} style={{marginLeft:'auto'}}><option value={0}>Any score</option><option value={60}>60+</option><option value={70}>70+</option><option value={80}>80+</option><option value={90}>90+</option></select></div></section>
<h2 style={{fontSize:20,margin:'0 0 4px'}}>Priority opportunities</h2><p style={{fontSize:12,color:'#7d8793',margin:'0 0 10px'}}>{rows.length} matching leads · category + score + pipeline filters applied</p><div style={{display:'grid',gap:10}}>{rows.map(x=>{const m=meta[x.id]||{},open=openId===x.id;return <article key={x.id} style={card}><div style={top}><div><div style={{display:'flex',alignItems:'center',gap:8}}><h3 style={{fontSize:15,margin:0}}>{x.name}</h3>{x.verification==='VERIFIED'?<ShieldCheck size={15}/>:<AlertTriangle size={15}/>}</div><div style={sub}><MapPin size={13}/>{x.city}, {x.state}{x.area?` · ${x.area}`:''}</div><div style={address}>{x.address||'Address not listed'}</div></div><div style={{textAlign:'right'}}><b style={{fontSize:22}}>{score(x)}</b><div style={{fontSize:9,color:'#7d8793'}}>OPPORTUNITY</div></div></div><div style={tags}><span style={tag}>{category(x)}</span>{x.services.map(s=><span key={s} style={tag}>{s}</span>)}</div><div style={bottom}><span style={sub}><Phone size={13}/>{x.phone||'Phone not listed'}</span><span style={source}>{x.rating?<><Star size={12} fill='currentColor'/> {x.rating} ({x.reviews||0}) · </>:''}{x.source||'Public listing'}</span><div style={{display:'flex',gap:6,marginLeft:'auto'}}><select value={m.status||'New'} onChange={e=>updateLead(x.id,{status:e.target.value as LeadStatus})}><option>New</option><option>Contacted</option><option>Qualified</option><option>Converted</option></select><button onClick={()=>updateLead(x.id,{saved:!m.saved})} style={smallBtn}><Save size={13}/>{m.saved?'Saved':'Save'}</button><button onClick={()=>setOpenId(open?null:x.id)} style={smallBtn}>{open?'Close':'Follow-up'}</button></div></div>{open&&<div style={follow}><label><StickyNote size={14}/><textarea value={m.notes||''} onChange={e=>updateLead(x.id,{notes:e.target.value})} placeholder='Notes about this agency...' style={{width:'100%',minHeight:70,border:'1px solid #dce1e6',borderRadius:7,padding:8}}/></label><label><CalendarDays size={14}/><input type='date' value={m.followUpDate||''} onChange={e=>updateLead(x.id,{followUpDate:e.target.value})} style={{display:'block',marginTop:6,width:'100%',border:'1px solid #dce1e6',borderRadius:7,padding:8}}/><span style={{display:'block',marginTop:8}}>Status: <b>{m.status||'New'}</b></span></label></div>}</article>})}{!rows.length&&<div style={{background:'#fff',padding:40,textAlign:'center',borderRadius:12}}>No matching agencies.</div>}</div><p style={{fontSize:10,color:'#9099a3',marginTop:18}}>National expansion is sourced from public directory listings. Imported Amadeus records are kept separate as AMADEUS IMPORTED and can be filtered before outreach.</p></div></main>}
function Stat({icon,value,label}:{icon:React.ReactNode,value:number|string,label:string}){return <div style={stat}><span>{icon}</span><div><b style={{fontSize:20}}>{value}</b><div style={{fontSize:10,color:'#7d8793'}}>{label}</div></div></div>}
const btn={border:'1px solid #d7dce1',background:'#fff',borderRadius:9,padding:'11px 14px',display:'flex',gap:7,alignItems:'center',cursor:'pointer'} as const,notice={background:'#eef6ff',border:'1px solid #cfe1f5',borderRadius:9,padding:'9px 12px',fontSize:11,marginBottom:12} as const,filters={display:'grid',gridTemplateColumns:'2fr repeat(5,1fr)',gap:9,background:'#fff',border:'1px solid #e1e5e9',borderRadius:12,padding:14,marginBottom:16} as const,searchBox={display:'flex',alignItems:'center',gap:8,border:'1px solid #e1e5e9',borderRadius:8,padding:'0 10px'} as const,stats={display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:10,marginBottom:18} as const,stat={background:'#fff',border:'1px solid #e1e5e9',borderRadius:11,padding:14,display:'flex',gap:10,alignItems:'center'} as const,panel={background:'#fff',border:'1px solid #e1e5e9',borderRadius:12,padding:14,marginBottom:18} as const,panelTitle={display:'flex',gap:8,alignItems:'center',marginBottom:10,fontWeight:800,fontSize:13} as const,wrap={display:'flex',gap:7,flexWrap:'wrap'} as const,pill={border:'1px solid #d7dce1',background:'#fff',borderRadius:999,padding:'7px 10px',cursor:'pointer',fontSize:11} as const,activePill={background:'#17202a',color:'#fff',borderColor:'#17202a'} as const,card={background:'#fff',border:'1px solid #e1e5e9',borderRadius:12,padding:16} as const,top={display:'flex',justifyContent:'space-between',gap:18} as const,sub={fontSize:11,color:'#6f7b88',display:'flex',gap:5,alignItems:'center',marginTop:6} as const,address={fontSize:11,color:'#8a949f',marginTop:5} as const,tags={display:'flex',flexWrap:'wrap',gap:6,margin:'12px 0'} as const,tag={background:'#f1f3f5',padding:'5px 8px',borderRadius:5,fontSize:9,color:'#64707e'} as const,bottom={display:'flex',justifyContent:'space-between',alignItems:'center',borderTop:'1px solid #edf0f2',paddingTop:11,gap:12,flexWrap:'wrap'} as const,source={fontSize:10,color:'#929ba6'} as const,smallBtn={border:'1px solid #d7dce1',background:'#fff',borderRadius:7,padding:'7px 9px',display:'flex',gap:5,alignItems:'center',cursor:'pointer',fontSize:11} as const,follow={marginTop:12,padding:12,borderRadius:9,background:'#f7f8fa',display:'grid',gridTemplateColumns:'1fr 180px',gap:10} as const;
